"""

Fee is responsible for the deduction of taxes generated by transactions and the recording of
bank income.

@Author Hengran Wu
"""
class Fee:
    money = 0

    def count(self,count,type):
        """
        Transaction taxes are calculated based on the amount and type of transaction

        Args:
            count(float):  Transaction amount
            type(str): Transaction type

        Returns:
            The actual amount received after deducting transaction taxes

        """
        if type == "Transfer to wallets":
            self.money += count*0.005
            return count*0.995
        elif type == "Transfer to other customers":
            self.money += count * 0.015
            return count*0.985
        else:
            return count